product_collection_name = '//span[@class="title__design h2"]'
product_article_name = '//span[@class="title__model p1"]'
product_is_out_of_stock = '//section[@class="StatusNote Card__StatusNote"]'
product_design_select = '//div[@class="Option__bubble-wrapper"]'
product_size_select = '//label[@class="SRadioButton Param__option option"]'
add_to_cart_button = '//button[@type="submit"]'
